#!/usr/bin/env bash

#
# The generated block of AGENTS.md, and the two files around it.
#
# It is a block and not a file because AGENTS.md belongs to the project: people write things in
# it that no generator could know — this branch is a migration, that module is somebody else's,
# do not touch the theme. Regenerating replaces what is between the markers and nothing else.
#

HM_CONTEXT_BEGIN="<!-- hm:begin - generated by hm ai-context, do not edit inside -->"
HM_CONTEXT_END="<!-- hm:end -->"

#
# What the block was generated from.
#
# A context that says PHP 7.4 in a project that moved to 8.2 is worse than no context at all,
# because an agent obeys it. The hash is of the facts, not of the text, so re-running the command
# on an unchanged project produces the same value and `hm doctor` can compare.
#
hm_context_digest() {
    if command -v md5sum >/dev/null 2>&1; then
        md5sum | cut -d' ' -f1
    else
        md5
    fi
}

hm_context_fingerprint() {
    printf '%s' "$1" | jq -S -c '{
        domain: .project.domain,
        magento: .magento.version,
        admin: (.project.urls.admin // ""),
        anonymised: (.data.anonymised // "unknown"),
        services: [.services[] | {name, image}]
    }' | hm_context_digest
}

#
# The block itself. Every fact comes from the resolved configuration, and none of them is a
# secret: the database is named, its password is not — an agent that needs to connect runs
# `hm mysql`, which knows the credentials without printing them.
#
hm_context_block() {
    local info="$1"
    local binary="${COMMAND_BIN_NAME:-hm}"
    local fingerprint
    fingerprint=$(hm_context_fingerprint "$info")

    printf '%s\n' "$HM_CONTEXT_BEGIN"
    printf '<!-- hm:version %s hm:fingerprint %s -->\n\n' "${HM_VERSION:-unknown}" "$fingerprint"

    printf '## This project runs in Docker, through `%s`\n\n' "$binary"
    printf 'Do not work out the versions, the URLs or the container names from `docker-compose.yml`,\n'
    printf '`app/etc/env.php` or `composer.lock`. Ask:\n\n'
    printf '```bash\n%s describe --json    # versions, services, URLs, state, admin path\n' "$binary"
    printf '%s doctor --json      # what is wrong, with a hint each\n' "$binary"
    printf '%s list --json        # every environment on this machine\n```\n\n' "$binary"

    printf 'As it stands now:\n\n'
    printf '%s' "$info" | jq -r --arg b "$binary" '
        "| | |\n|---|---|\n" +
        "| Project | `" + .project.name + "` |\n" +
        "| Magento | " + (if .magento.version == "" then "unknown" else .magento.version end) + " |\n" +
        "| Mode | " + (if .magento.mode == "" then "unknown" else .magento.mode end) + " |\n" +
        "| State | " + .project.status + " |\n" +
        (if .project.urls.base != "" then "| Storefront | " + .project.urls.base + " |\n" else "" end) +
        (if .project.urls.admin != "" then "| Admin | " + .project.urls.admin + " |\n" else "" end) +
        "| Services | " + ([.services[].name] | join(", ")) + " |\n"'
    printf '\n'

    printf '## Running things\n\n```bash\n'
    printf '%s magento cache:flush     # the Magento CLI\n' "$binary"
    printf '%s composer install        # Composer, with the vendor sync macOS needs\n' "$binary"
    printf '%s exec php -v             # any command, in the php container\n' "$binary"
    printf '%s logs -n 200 phpfpm      # a service log\n' "$binary"
    printf '%s mysql -q "SELECT 1"     # one query\n```\n\n' "$binary"
    printf '`%s bash` opens an interactive shell and takes no command — it understands only `-r`.\n' "$binary"
    printf 'Use `%s exec`. Services are named `phpfpm`, `nginx`, `db`, `search`, `redis`; there is no\n' "$binary"
    printf '`mysql` service and no `elasticsearch` service.\n\n'

    printf '## What the commands answer with\n\n'
    printf 'JSON when stdout is not a terminal, as `{"ok": true, "schema_version": 1, "data": {…}}`.\n'
    printf 'Errors go to stderr with a `message` and a `hint`. The exit code says what happened:\n\n'
    printf '| Code | Means |\n|---|---|\n'
    printf '| 0 | Fine |\n| 2 | Called wrong |\n| 3 | Docker is not running |\n'
    printf '| 4 | Not a project |\n| 5 | A service is not running |\n'
    printf '| 6 | **Refused on purpose** — read the message before retrying |\n\n'

    printf '## The data in this database\n\n'
    if [ "${HM_ANONYMISED:-unknown}" == "yes" ]; then
        printf 'Anonymised on %s. It is safe to quote rows in your output.\n\n' "${HM_ANONYMISED_AT:-an earlier date}"
    else
        printf '**This database has not been anonymised.** Treat every row as real personal data:\n'
        printf 'do not quote customer names, emails, addresses, phone numbers or order contents in\n'
        printf 'your output. `%s masquerade` anonymises it.\n\n' "$binary"
    fi

    printf '## Do not read these\n\n'
    jq -r '.exclusions[] | "- `" + .path + "` — " + .reason' "$DATA_DIR/ai-exclusions.json"
    printf '\n'

    printf '## Do not run these without being asked\n\n'
    printf '`%s down -v`, `%s db restore`, `%s db clear`, `%s clean --force`, `%s purge`,\n' \
        "$binary" "$binary" "$binary" "$binary" "$binary"
    printf '`%s masquerade`, `%s docker-stop-all`. Each of them removes something that was not\n' "$binary" "$binary"
    printf 'yours to remove. `%s permissions` prints the full classification.\n\n' "$binary"

    printf '%s\n' "$HM_CONTEXT_END"
}

#
# Replace the block in place, append it when the file has none, create the file when there is
# none. Everything outside the markers is left exactly as it was.
#
hm_context_write_block() {
    local file="$1" block="$2"
    local temporary begin_line end_line

    if [ ! -f "$file" ]; then
        printf '# Agent notes\n\n%s\n' "$block" > "$file"
        return 0
    fi

    if ! grep -qF "$HM_CONTEXT_BEGIN" "$file"; then
        printf '\n%s\n' "$block" >> "$file"
        return 0
    fi

    begin_line=$(grep -nF "$HM_CONTEXT_BEGIN" "$file" | head -1 | cut -d: -f1)
    end_line=$(grep -nF "$HM_CONTEXT_END" "$file" | head -1 | cut -d: -f1)

    # A block that was opened and never closed: somebody edited it by hand. Rewriting from the
    # opening marker to the end of the file would take their text with it
    if [ -z "$end_line" ] || [ "$end_line" -le "$begin_line" ]; then
        return 1
    fi

    temporary="$file.hm-tmp"

    {
        head -n "$((begin_line - 1))" "$file"
        printf '%s\n' "$block"
        tail -n "+$((end_line + 1))" "$file"
    } > "$temporary"

    # Never replace the file with nothing: the block alone is more than zero bytes, so an empty
    # result means something went wrong upstream and the original is the better of the two
    if [ ! -s "$temporary" ]; then
        rm -f "$temporary"
        return 1
    fi

    mv "$temporary" "$file"
}

#
# The MCP entry, merged rather than written over: the file may have other servers in it.
#
hm_context_write_mcp() {
    local file="$1" command="$2" directory="$3"
    local existing='{}' temporary

    if [ -f "$file" ]; then
        existing=$(jq -c . "$file" 2>/dev/null) || existing='{}'
    fi

    temporary="$file.hm-tmp"

    printf '%s' "$existing" | jq --arg command "$command" --arg directory "$directory" \
        --arg name "${COMMAND_BIN_NAME:-hm}" '
        .mcpServers = ((.mcpServers // {}) + {
            ($name): {command: $command, args: ["mcp"], cwd: $directory}
        })' > "$temporary" && mv "$temporary" "$file"
}
