#!/usr/bin/env bash

#
# The global proxy: one per machine, so that more than one project can be up at a time.
#
# It lives in ~/.hm/proxy as an ordinary Compose project called `hm-proxy`, next to the cache and
# the snapshots. That way it shows up in `docker ps` under a name anybody recognises and can be
# stopped by hand without magic.
#
# Projects reach it through a shared Docker network. Only HTTP is routed by name: MySQL and AMQP
# carry no hostname —Traefik says so itself, `has HostSNI matcher, but no TLS on router`— and are
# reached with `hm tunnel` instead.
#

HM_PROXY_DIR="${HM_PROXY_DIR:-$HOME/.hm/proxy}"
HM_PROXY_PROJECT="hm-proxy"
HM_PROXY_NETWORK="hm-gateway"
HM_PROXY_IMAGE="traefik:v3.3"

# `!reset`, which is what lets a project drop its published ports without duplicating the
# template, arrived in Compose 2.24
HM_PROXY_MIN_COMPOSE="2.24"

hm_proxy_compose() {
    printf '%s -p %s -f %s/docker-compose.yml' \
        "$(get_docker_compose_cmd)" "$HM_PROXY_PROJECT" "$HM_PROXY_DIR"
}

#
# Does this Compose understand the overlay the projects need?
#
hm_proxy_compose_is_recent_enough() {
    local version
    version=$(get_docker_compose_version)

    local have_major="${version%%.*}"
    local rest="${version#*.}"
    local have_minor="${rest%%.*}"
    local want_major="${HM_PROXY_MIN_COMPOSE%%.*}"
    local want_minor="${HM_PROXY_MIN_COMPOSE#*.}"

    [ "${have_major:-0}" -gt "$want_major" ] && return 0
    [ "${have_major:-0}" -lt "$want_major" ] && return 1
    [ "${have_minor:-0}" -ge "$want_minor" ]
}

#
# Write the proxy's own compose file. Regenerated every time: it is ours, nobody edits it, and a
# stale one is harder to notice than a rewritten one.
#
#
# The proxy's configuration is shared by every project on the machine, so it is written through a
# temporary and a rename, and only when it actually changes: rewriting it on every `proxy up` is
# a global file being mutated while other projects may be reading it, for no gain.
#
hm_proxy_write_compose() {
    mkdir -p "$HM_PROXY_DIR/dynamic" "$HM_PROXY_DIR/certs"

    local temporary
    temporary=$(mktemp "$HM_PROXY_DIR/docker-compose.yml.XXXXXX") || return 1

    cat > "$temporary" <<YAML
# Generated by $COMMAND_BIN_NAME. Edits are lost on the next start.
services:
  traefik:
    image: $HM_PROXY_IMAGE
    container_name: hm-proxy
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=$HM_PROXY_NETWORK
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
      # The dashboard is bound to loopback: it exposes what is routed where, and that is
      # nobody else's business on a shared network
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./certs:/etc/traefik/certs:ro
    networks:
      - default

networks:
  default:
    name: $HM_PROXY_NETWORK
    external: true
YAML

    if cmp -s "$temporary" "$HM_PROXY_DIR/docker-compose.yml" 2>/dev/null; then
        rm -f "$temporary"
        return 0
    fi

    mv "$temporary" "$HM_PROXY_DIR/docker-compose.yml"
}

#
# The shared network, created before anything tries to join it
#
hm_proxy_ensure_network() {
    docker network inspect "$HM_PROXY_NETWORK" >/dev/null 2>&1 && return 0
    docker network create "$HM_PROXY_NETWORK" >/dev/null 2>&1
}

#
# Who is holding the ports the proxy needs.
#
# The proxy listens on 80 and 443; a project that does *not* use it publishes those itself. So the
# two cannot be up at the same time, and saying which project is in the way is far more useful than
# Docker's "port is already allocated".
#
hm_proxy_port_holder() {
    local port
    for port in 80 443; do
        docker ps --format '{{.Names}}\t{{.Ports}}' 2>/dev/null |
            awk -F'\t' -v port=":$port->" '$2 ~ port { print $1; exit }'
    done | grep -v '^hm-proxy$' | head -1
}

hm_proxy_is_running() {
    [ -n "$(docker ps -q --filter "name=^hm-proxy$" 2>/dev/null)" ]
}

hm_proxy_up() {
    hm_proxy_ensure_network
    hm_proxy_write_compose
    $(hm_proxy_compose) up -d >/dev/null 2>&1
}

hm_proxy_down() {
    [ -f "$HM_PROXY_DIR/docker-compose.yml" ] || return 0
    $(hm_proxy_compose) down >/dev/null 2>&1
}

#
# What the proxy is routing, straight from its own API rather than from our idea of it
#
hm_proxy_routes() {
    curl -s --max-time 3 http://127.0.0.1:8080/api/http/routers 2>/dev/null |
        jq -r '.[]? | select(.provider == "docker") |
            "\(.rule // "" | capture("Host\\(`(?<host>[^`]*)`\\)").host // "")\t\(.status)"' \
        2>/dev/null | sed '/^\t/d' | sort -u
}

#
# A wildcard certificate for the project's domain.
#
# Wildcard because the auxiliary interfaces live on subdomains, and a certificate per domain does
# not cover them. mkcert is already a dependency of `hm ssl`.
#
hm_proxy_write_certificate() {
    local domain="$1"

    command -v mkcert >/dev/null 2>&1 || return 1

    mkdir -p "$HM_PROXY_DIR/certs" "$HM_PROXY_DIR/dynamic"

    local cert="$HM_PROXY_DIR/certs/$domain.pem"
    local key="$HM_PROXY_DIR/certs/$domain-key.pem"

    mkcert -cert-file "$cert" -key-file "$key" "$domain" "*.$domain" >/dev/null 2>&1 || return 1

    cat > "$HM_PROXY_DIR/dynamic/$domain.yml" <<YAML
# Generated by $COMMAND_BIN_NAME for $domain
tls:
  certificates:
    - certFile: /etc/traefik/certs/$domain.pem
      keyFile: /etc/traefik/certs/$domain-key.pem
YAML
}

#
# Is this project routed through the proxy?
#
hm_project_uses_proxy() {
    case "${USE_PROXY:-false}" in
        true | yes | 1) return 0 ;;
        *) return 1 ;;
    esac
}

#
# The overlay that routes this project through the global proxy.
#
# Written as a separate file rather than a second template, because Compose 2.24 can *remove* keys
# with `!reset`: `ports: !reset []` leaves a service with nothing published and `hitch: !reset null`
# deletes the service outright. So the base template never has to know the proxy exists, and there
# is one template to maintain instead of two that drift apart.
#
# Hitch is dropped on purpose. It is in the stack for one reason — giving Varnish the HTTPS it does
# not have — and with the proxy terminating TLS it solves nothing any more.
#
hm_proxy_write_overlay() {
    local mail_service="${MAIL_SERVICE:-mailhog}"
    local domain="${DOMAIN:-localhost}"
    local project="${COMPOSE_PROJECT_NAME}"
    local file="${DOCKER_COMPOSE_FILE%.yml}.proxy.yml"

    #
    # Every routed service joins the shared network and gets a router. The auxiliary interfaces
    # live on subdomains, so each believes it is at its own root — served under a path prefix,
    # most of them generate absolute links and break.
    #
    # Every service appears exactly once. A repeated key in YAML is not a merge: the last one
    # wins and the earlier block is dropped silently, which is how four services quietly kept
    # their published ports the first time this was written.
    {
        printf '# Generated by %s. Edits are lost on the next `setup -f`.\n' "$COMMAND_BIN_NAME"
        printf 'services:\n'

        local service
        for service in phpfpm nginx db redis; do
            printf '  %s:\n    ports: !reset []\n' "$service"
        done

        _hm_proxy_service "varnish"       "$project"        "$domain"        "6081"
        _hm_proxy_service "$mail_service" "$project-mail"   "mail.$domain"   "8025"
        _hm_proxy_service "rabbitmq"      "$project-queue"  "queue.$domain"  "15672"
        _hm_proxy_service "search"        "$project-search" "search.$domain" "9200"

        # Hitch existed only to put TLS in front of Varnish
        printf '  hitch: !reset null\n'

        printf 'networks:\n  %s:\n    external: true\n' "$HM_PROXY_NETWORK"
    } > "$file"
}

#
# _proxy_service <service> <router name> <host> <container port>
#
# One block per service: it stops publishing, joins the shared network, and gets its router.
#
_hm_proxy_service() {
    cat <<YAML
  $1:
    ports: !reset []
    networks:
      - default
      - $HM_PROXY_NETWORK
    labels:
      traefik.enable: "true"
      traefik.docker.network: "$HM_PROXY_NETWORK"
      traefik.http.routers.$2.rule: "Host(\`$3\`)"
      traefik.http.routers.$2.entrypoints: "websecure"
      traefik.http.routers.$2.tls: "true"
      traefik.http.services.$2.loadbalancer.server.port: "$4"
YAML
}
