#!/usr/bin/env bash
set -uo pipefail

source "$COMPONENTS_DIR"/print_message.sh
source "$COMPONENTS_DIR"/print_json.sh
source "$HELPERS_DIR"/exit_codes.sh
source "$TASKS_DIR"/collect_project_info.sh
source "$TASKS_DIR"/agent_context.sh

#
# What an agent needs to know about this project, written where it will read it.
#
# Everything here is already answerable — `hm describe` has resolved the versions, the URLs and
# the admin's real front name since 1.5. What was missing is that anybody thought to ask: an
# agent that is not told the command exists works the facts out from docker-compose.yml and
# composer.lock, and gets the configured value instead of the resolved one, or invents /admin and
# reports the 404 as a bug.
#
# The same file has to say what not to read. app/etc/env.php holds the encryption key, var/log
# holds whatever the site logged about real customers, and an agent reads a project by default.
#

usage() {
    print_info "Write the project context an agent reads before it starts\n\n"
    print_default "  $COMMAND_BIN_NAME ai-context\n\n"
}

case "${1:-}" in
    "") ;;
    --help | -h) usage; exit 0 ;;
    *)
        hm_fail "$HM_EXIT_USAGE" "invalid_argument" "Unknown option: $1" \
            "$COMMAND_BIN_NAME ai-context"
        ;;
esac

info=$(collect_project_info false)

if [ -z "$info" ] || [ "$(printf '%s' "$info" | jq -r '.project.name // ""')" == "" ]; then
    hm_fail "$HM_EXIT_PROJECT" "no_project" \
        "There is no project here to describe" \
        "$COMMAND_BIN_NAME setup"
fi

root="${HM_ROOT:-$PWD}"
agents_file="$root/AGENTS.md"
claude_file="$root/CLAUDE.md"
mcp_file="$root/.mcp.json"

written=""
block=$(hm_context_block "$info")

if ! hm_context_write_block "$agents_file" "$block"; then
    hm_fail "$HM_EXIT_BLOCKED" "block_not_closed" \
        "AGENTS.md has an opening marker with no closing one, so the block cannot be replaced" \
        "Restore the $(printf '%s' "$HM_CONTEXT_END") line, or delete the block and run this again"
fi

written="AGENTS.md"

#
# A CLAUDE.md is the first thing somebody wrote about their project. It is created when it is
# missing and never touched when it is not: the line to add is printed instead.
#
claude_note=""
if [ ! -f "$claude_file" ]; then
    printf '@AGENTS.md\n' > "$claude_file"
    written="$written CLAUDE.md"
else
    grep -q 'AGENTS.md' "$claude_file" || claude_note="@AGENTS.md"
fi

hm_context_write_mcp "$mcp_file" "$COMMAND_BIN_DIR/bin/run" "$root"
written="$written .mcp.json"

if is_json_output; then
    json_success "ai-context" "$(jq -n --arg written "$written" --arg root "$root" \
        --arg claude_note "$claude_note" \
        '{written: ($written | split(" ")), root: $root,
          claude_needs: (if $claude_note == "" then null else $claude_note end)}')"
    exit 0
fi

printf '\n'
print_info "Wrote "
print_code "$written"
printf '\n'
print_default "  The block in AGENTS.md is regenerated by this command; anything outside it is yours.\n"

if [ -n "$claude_note" ]; then
    printf '\n'
    print_warning_line "CLAUDE.md already exists and was not touched"
    print_default "  Add this line to it so the context is loaded:\n\n    "
    print_code "@AGENTS.md"
    printf '\n'
fi

printf '\n'
print_default "  Re-run it when the project changes: "
print_code "$COMMAND_BIN_NAME doctor"
print_default " says when it has gone stale.\n\n"
