package cli

import (
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/hiberus-magento/hiberus-dockergento/internal/adapters/fsprops"
	"github.com/hiberus-magento/hiberus-dockergento/internal/adapters/gitvcs"
	"github.com/hiberus-magento/hiberus-dockergento/internal/adapters/osfs"
	"github.com/hiberus-magento/hiberus-dockergento/internal/app"
	"github.com/hiberus-magento/hiberus-dockergento/internal/core"
)

// resolveProject answers what project the current directory belongs to.
func resolveProject() (core.Project, error) {
	directory, err := os.Getwd()
	if err != nil {
		return core.Project{}, err
	}

	resolver := app.Resolver{
		Properties: fsprops.Reader{Defaults: defaultsFile()},
		VCS:        gitvcs.Git{},
		Registry:   registry{},
	}

	return resolver.Resolve(directory)
}

// properties re-reads the project's file. It is a small JSON and the alternative is carrying a map
// through every layer that might one day need one value from it.
func properties(project core.Project) map[string]string {
	values, err := (fsprops.Reader{Defaults: defaultsFile()}).Load(project.Root)
	if err != nil {
		return map[string]string{}
	}

	return values
}

func property(project core.Project, key string) string {
	return properties(project)[key]
}

// composeFilesFor is what the project is built from.
//
// Two files the project declares — its own and the overlay for this platform — and up to one more
// that it does not:
//
//   - a project routed through the global proxy carries a third file that removes its published
//     ports and adds the routing. It is generated by `setup`, so its absence just means this
//     project does not use the proxy.
//   - a branch environment carries an overlay that lives outside the checkout, next to its
//     registration, and carries its profile and its address. It is loaded instead of the proxy's,
//     never as well: the proxy overlay claims the main environment's address.
//
// Loading the wrong list is not a cosmetic mistake. Without the proxy overlay a proxied project
// reads as publishing ports it does not publish; without the worktree overlay a branch
// environment reads as the main one.
func composeFilesFor(project core.Project) core.ComposeFiles {
	values := properties(project)

	base := values["DOCKER_COMPOSE_FILE"]
	if base == "" {
		base = "docker-compose.yml"
	}

	overlay := values["DOCKER_COMPOSE_FILE_LINUX"]
	if runtime.GOOS == "darwin" {
		overlay = values["DOCKER_COMPOSE_FILE_MAC"]
	}

	if overlay == "" {
		overlay = "docker-compose.dev." + map[bool]string{true: "mac", false: "linux"}[runtime.GOOS == "darwin"] + ".yml"
	}

	files := core.ComposeFiles{
		Load:     []string{base, overlay},
		Declared: []string{base, overlay},
	}

	if project.Worktree != nil {
		files.Load = append(files.Load, registry{}.Overlay(project.Worktree.Parent, project.Worktree.Name))

		return files
	}

	proxy := strings.TrimSuffix(base, ".yml") + ".proxy.yml"
	if (osfs.FS{}).Exists(filepath.Join(project.Root, proxy)) {
		files.Load = append(files.Load, proxy)
	}

	return files
}

// environmentFor is what the variables inside the compose files interpolate against: the process's
// environment with the project's properties on top, which is what `set -a` did in the shell
// implementation.
func environmentFor(project core.Project) map[string]string {
	environment := map[string]string{}

	for _, entry := range os.Environ() {
		for at := 0; at < len(entry); at++ {
			if entry[at] == '=' {
				environment[entry[:at]] = entry[at+1:]

				break
			}
		}
	}

	for key, value := range properties(project) {
		environment[key] = value
	}

	environment["COMPOSE_PROJECT_NAME"] = project.Name
	environment["HM_ROOT"] = project.Root

	return environment
}

// defaultsFile is the tool's own properties, which a project's are merged over — the same merge
// the shell implementation does, and the reason a project that never set WORKDIR_PHP still has
// one.
func defaultsFile() string {
	root := hmRoot()
	if root == "" {
		return ""
	}

	return filepath.Join(root, "data", "properties.json")
}

// hmRoot is the tool's own directory, for the version it reports.
func hmRoot() string {
	executable, err := os.Executable()
	if err != nil {
		return ""
	}

	if resolved, err := filepath.EvalSymlinks(executable); err == nil {
		executable = resolved
	}

	return filepath.Dir(filepath.Dir(executable))
}
