package core

import (
	"fmt"
	"strconv"
	"strings"
)

//
// The global proxy: one per machine, so that more than one project can be up at a time.
//
// It is an ordinary Compose project called `hm-proxy`, living beside the cache and the snapshots,
// so it shows up in `docker ps` under a name anybody recognises and can be stopped by hand without
// magic. Projects reach it through a shared Docker network.
//
// Only HTTP is routed by name. MySQL and AMQP carry no hostname — Traefik says so itself, `has
// HostSNI matcher, but no TLS on router` — and are reached through a tunnel instead.
//

const (
	// ProxyProject is the compose project it runs as, and ProxyContainer the container's name.
	ProxyProject   = "hm-proxy"
	ProxyContainer = "hm-proxy"

	// ProxyNetwork is the shared network projects join to be routed.
	ProxyNetwork = "hm-gateway"

	// ProxyImage is pinned: a proxy that upgrades itself underneath a machine full of running
	// projects is a morning spent finding out why.
	ProxyImage = "traefik:v3.3"

	// ProxyMinCompose is where `!reset` arrived, which is what lets a project drop its published
	// ports without a second template to maintain.
	ProxyMinCompose = "2.24"
)

// ProxyPorts are what it listens on, and what a project that does not use it holds itself.
var ProxyPorts = []string{"80", "443"}

// ProxyCompose is the proxy's own compose file.
//
// Generated rather than shipped, and rewritten only when it changes: it is ours, nobody edits it,
// and a stale one is harder to notice than a rewritten one.
func ProxyCompose(binary string) string {
	return fmt.Sprintf(`# Generated by %s. Edits are lost on the next start.
services:
  traefik:
    image: %s
    container_name: %s
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=%s
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
      # The dashboard is bound to loopback: it exposes what is routed where, and that is
      # nobody else's business on a shared network
      - "127.0.0.1:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dynamic:/etc/traefik/dynamic:ro
      - ./certs:/etc/traefik/certs:ro
    networks:
      - default

networks:
  default:
    name: %s
    external: true
`, binary, ProxyImage, ProxyContainer, ProxyNetwork, ProxyNetwork)
}

// ProxyCertificate is the dynamic configuration that tells the proxy which certificate serves a
// domain.
func ProxyCertificate(binary, domain string) string {
	return fmt.Sprintf(`# Generated by %s for %s
tls:
  certificates:
    - certFile: /etc/traefik/certs/%s.pem
      keyFile: /etc/traefik/certs/%s-key.pem
`, binary, domain, domain, domain)
}

// Route is one thing the proxy is routing, as the proxy itself reports it.
type Route struct {
	Host   string `json:"host"`
	Status string `json:"status"`
}

// ProxyState is what `proxy status` answers.
type ProxyState struct {
	Running bool    `json:"running"`
	Network string  `json:"network"`
	Routes  []Route `json:"routes"`
}

// ComposeAtLeast compares two versions by major and minor, which is as much as this needs to know.
//
// A version that cannot be read counts as too old: refusing something that would work is a
// sentence somebody can act on, and letting through something that will not is an overlay that
// silently keeps its published ports.
func ComposeAtLeast(have, want string) bool {
	haveMajor, haveMinor := versionParts(have)
	wantMajor, wantMinor := versionParts(want)

	if haveMajor != wantMajor {
		return haveMajor > wantMajor
	}

	return haveMinor >= wantMinor
}

func versionParts(version string) (int, int) {
	version = strings.TrimPrefix(strings.TrimSpace(version), "v")
	parts := strings.SplitN(version, ".", 3)

	major, _ := strconv.Atoi(parts[0])
	minor := 0

	if len(parts) > 1 {
		minor, _ = strconv.Atoi(parts[1])
	}

	return major, minor
}
