package core

import (
	"fmt"
	"strings"
)

//
// The overlay that turns the project's configuration into this branch's environment.
//
// It does the whole job on its own — the profile, the ports and the routing — because the
// project's own proxy overlay must NOT be loaded beside it: that one claims the main
// environment's Host rule, and two containers claiming one rule is a router that answers with
// either.
//

// OverlayFor is the compose file for one branch environment.
//
// Pure, so that what it writes can be read in a test rather than by standing an environment up:
// the mistakes it can make — a service written twice, a router pointing at a service that was
// removed — are all invisible until something is running.
func OverlayFor(binary, router, profile, domain, network string, services []string, mounts []string) string {
	keeps, _ := ProfileKeeps(profile)
	web, port := WebService(profile)

	// A profile that keeps no web service answers on no address: `lite` is code without HTTP, and
	// a router pointing at a service that was removed is a 404 with an explanation nobody has
	if len(keeps) > 0 && !contains(keeps, web) {
		web = ""
	}

	var overlay strings.Builder

	fmt.Fprintf(&overlay,
		"# Generated by %s for the branch environment %s. Edits are lost.\n", binary, router)
	overlay.WriteString("services:\n")

	//
	// Every service written exactly once. A repeated key in YAML is not a merge: the last one
	// wins and the earlier block disappears without a word.
	//
	for _, service := range services {
		if len(keeps) > 0 && !contains(keeps, service) {
			fmt.Fprintf(&overlay, "  %s: !reset null\n", service)

			continue
		}

		fmt.Fprintf(&overlay, "  %s:\n    ports: !reset []\n", service)

		if len(keeps) > 0 {
			overlay.WriteString("    depends_on: !reset []\n")
		}

		if service == web {
			fmt.Fprintf(&overlay, "    networks:\n      - default\n      - %s\n", network)
			overlay.WriteString("    labels:\n")
			overlay.WriteString("      traefik.enable: \"true\"\n")
			fmt.Fprintf(&overlay, "      traefik.docker.network: \"%s\"\n", network)
			fmt.Fprintf(&overlay, "      traefik.http.routers.%s.rule: \"Host(`%s`)\"\n", router, domain)
			fmt.Fprintf(&overlay, "      traefik.http.routers.%s.entrypoints: \"websecure\"\n", router)
			fmt.Fprintf(&overlay, "      traefik.http.routers.%s.tls: \"true\"\n", router)
			fmt.Fprintf(&overlay,
				"      traefik.http.services.%s.loadbalancer.server.port: \"%s\"\n", router, port)
		}

		//
		// Only on phpfpm: that is where PHP runs, and where `__DIR__` has to resolve inside the
		// worktree rather than behind a link into the main checkout. Compose appends volume
		// entries across files, so this sits on top of the code mount without disturbing it.
		//
		if service == "phpfpm" && len(mounts) > 0 {
			overlay.WriteString("    volumes:\n")

			for _, mount := range mounts {
				fmt.Fprintf(&overlay, "      - %s\n", mount)
			}
		}
	}

	fmt.Fprintf(&overlay, "networks:\n  %s:\n    external: true\n", network)

	return overlay.String()
}

func contains(values []string, wanted string) bool {
	for _, value := range values {
		if value == wanted {
			return true
		}
	}

	return false
}
