package dockergento

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/hiberus-magento/hiberus-dockergento/dockergento/core"
)

// motor is an engine that reads no installed tool: the fixtures below declare everything they
// need, and picking up whatever properties happen to be installed on the machine running the
// tests is how a test passes somewhere and fails everywhere else.
func motor(t *testing.T) *Engine {
	t.Helper()

	return New(Options{Root: t.TempDir()})
}

// proyecto writes a project on disk and answers where it is.
func proyecto(t *testing.T, properties string, files ...string) core.Project {
	t.Helper()

	root := t.TempDir()

	if err := os.MkdirAll(filepath.Join(root, "config", "docker"), 0o755); err != nil {
		t.Fatalf("creating the project = %v, want no error", err)
	}

	if err := os.WriteFile(filepath.Join(root, "config", "docker", "properties.json"),
		[]byte(properties), 0o644); err != nil {
		t.Fatalf("writing the properties = %v, want no error", err)
	}

	for _, file := range files {
		if err := os.WriteFile(filepath.Join(root, file), []byte("services: {}\n"), 0o644); err != nil {
			t.Fatalf("writing %s = %v, want no error", file, err)
		}
	}

	return core.Project{Name: "tienda", Root: root, MagentoDir: "."}
}

func has(files []string, wanted string) bool {
	for _, file := range files {
		if filepath.Base(file) == wanted {
			return true
		}
	}

	return false
}

//
// The tool has to serve both: a project that wants the global proxy and one that does not. The
// difference is a generated overlay that removes the published ports and adds the routing, so
// loading it when it is not there — or not loading it when it is — makes the project read as
// something it is not.
//

func TestAProjectThatDoesNotUseTheProxy(t *testing.T) {
	project := proyecto(t, `{"COMPOSE_PROJECT_NAME": "tienda"}`)

	files := motor(t).ComposeFiles(project)

	if len(files.Load) != 2 {
		t.Fatalf("files to load without the proxy = %d (%v), want 2", len(files.Load), files.Load)
	}

	if has(files.Load, "docker-compose.proxy.yml") {
		t.Fatal("the proxy overlay is loaded, want it left out")
	}
}

func TestAProjectRoutedThroughTheProxy(t *testing.T) {
	project := proyecto(t, `{"COMPOSE_PROJECT_NAME": "tienda", "USE_PROXY": "true"}`,
		"docker-compose.proxy.yml")

	files := motor(t).ComposeFiles(project)

	if !has(files.Load, "docker-compose.proxy.yml") {
		t.Fatalf("files to load = %v, want the proxy overlay among them", files.Load)
	}
}

func TestTheOverlayIsLoadedBecauseItIsThereAndNotBecauseOfAFlag(t *testing.T) {
	// It is generated by `setup`, so its absence is the answer: a project that turned the proxy
	// on and has not been set up again is still publishing its ports
	project := proyecto(t, `{"COMPOSE_PROJECT_NAME": "tienda", "USE_PROXY": "true"}`)

	if has(motor(t).ComposeFiles(project).Load, "docker-compose.proxy.yml") {
		t.Fatal("a file that is not there is loaded, want it left out")
	}
}

func TestWhatADescriptionReportsIsWhatTheProjectDeclares(t *testing.T) {
	// The overlays are the tool's business, not the project's: reporting them would be reporting
	// files nobody wrote
	project := proyecto(t, `{"COMPOSE_PROJECT_NAME": "tienda", "USE_PROXY": "true"}`,
		"docker-compose.proxy.yml")

	files := motor(t).ComposeFiles(project)

	if len(files.Declared) != 2 || has(files.Declared, "docker-compose.proxy.yml") {
		t.Fatalf("declared files = %v, want the two the project declares", files.Declared)
	}
}

func TestABranchEnvironmentTakesItsOwnOverlayAndNotTheProxys(t *testing.T) {
	// The proxy overlay claims the main environment's address, so a branch environment loading it
	// would answer on somebody else's domain
	registrations := t.TempDir()
	t.Setenv("HM_WORKTREE_DIR", registrations)

	if err := os.MkdirAll(filepath.Join(registrations, "tienda"), 0o755); err != nil {
		t.Fatalf("creating the registry = %v, want no error", err)
	}

	project := proyecto(t, `{"COMPOSE_PROJECT_NAME": "tienda", "USE_PROXY": "true"}`,
		"docker-compose.proxy.yml")
	project.Worktree = &core.Worktree{Name: "rama", Parent: "tienda"}

	files := motor(t).ComposeFiles(project)

	if has(files.Load, "docker-compose.proxy.yml") {
		t.Fatalf("files to load = %v, want the main environment's proxy overlay left out", files.Load)
	}

	if !has(files.Load, "rama.yml") {
		t.Fatalf("files to load = %v, want the branch's own overlay among them", files.Load)
	}
}

// Everywhere else nothing is handed over. A registration that does not apply is worse than none,
// because the shell half trusts what it is given.
func TestNothingIsHandedOverOutsideABranchEnvironment(t *testing.T) {
	project := proyecto(t, `{"COMPOSE_PROJECT_NAME": "tienda"}`)

	if handed := motor(t).registration(project.Root); len(handed) != 0 {
		t.Fatalf("handed over from a main checkout = %v, want nothing", handed)
	}

	if handed := motor(t).registration(filepath.Join(project.Root, "no", "existe")); len(handed) != 0 {
		t.Fatalf("handed over from a directory that is not a project = %v, want nothing", handed)
	}
}
